// import { TaskManagementComponent } from '../../task-management/task-management.component';

export const UrlModel = {
  Auth: {
    Login: 'Auth/login',
    ChangePassword: 'Auth/ChangePassword'
  },
  ManageAgent: {
    GetAgentDetails: 'ManageAgents/GetAgentDetails',
    AddAgent: 'ManageAgents/AddAgents',
    SearchAgent: 'ManageAgents/searchagents',
    AllAgents: 'ManageAgents/AllAgents',
    AllDraftAgents: 'ManageAgents/AllDraftAgents',
    EditAgent: 'ManageAgents/EditAgents',
    UpdateAgentLogo: 'ManageAgents/UpdateAgentLogo',
  },
  ManageEmployee:
  {
    AddEmployee: 'ManageEmployees/AddEmployee',
    SearchEmployee: 'ManageEmployees/SearchEmployees',
    GetEmployeeDetails: 'ManageEmployees/GetEmployeeDetails',
    EditEmployee: 'ManageEmployees/EditEmployee',
    AllRoles: 'ManageEmployees/AllRoles', 
    AllInspector: 'ManageEmployees/AllInspectors',
    AllEmployees: 'ManageEmployees/GetAllEmployees',
    AddEmployeeGroup: 'ManageEmployees/AddEmployeeGroup',
    GetAllEmployeeGroup: 'ManageEmployees/GetAllEmployeeGroup',
    GetEmployeeGroupById: 'ManageEmployees/GetEmployeeGroupById',
    AddCheckListOption: 'ManageEmployees/AddCheckListOption',
    GetCheckListOption: 'ManageEmployees/GetCheckListOption',
    GetCheckListGroup: 'ManageEmployees/GetCheckListGroup',
    AddCheckListGroup: 'ManageEmployees/AddCheckListGroup',
    AddAssignCheckListGroup: 'ManageEmployees/AddAssignCheckListGroup',
    GetAllAssignCheckListGroup: 'ManageEmployees/GetAllAssignCheckListGroup',
    GetAllAssignCheckListGroupById: 'ManageEmployees/GetAllAssignCheckListGroupById',
    AssignCheckListStatusUpdate: 'ManageEmployees/AssignCheckListStatusUpdate',
    UpdateEmployeeProfilePicture: 'ManageEmployees/UpdateEmployeeProfilePicture',
    AllActiveEmployee: 'ManageEmployees/AllActiveEmployee',
    EmployeeRequest : 'ManageEmployees/GetEmployeeRequestSummary'
  },
  ManageSalePointUser: {
    MembershipType: 'SalesPoint/MembershipTypes',
    AddSalePointUser: 'ManageSalePointUser/AddSalePointUser',
    GetUserDetails: 'ManageSalePointUser/GetSalesPointUserDetails',
    EditSalesUser: 'ManageSalePointUser/EditSalePointUser',
    SearchSalesPointUser: 'ManageSalePointUser/searchsalespointusers',
    AllSalesPoint: 'Common/AllSalesPoint'
  },
  ManageLocations: {
    GetLocationDetails: 'ManageLocations/GetLocationDetails',
    AddLocation: 'ManageLocations/AddLocation',
    EditLocation: 'ManageLocations/EditLocation',
    SearchLocation: 'ManageLocations/SearchLocations',
    AllLocations: 'ManageLocations/AllLocations',
    LocationByAgent: 'ManageLocations/LocationByAgent',
  },
  ManageAreas:{
    AddUpdateUaeAreas: 'ManageAreas/AddUpdateUaeAreas',
    SearchAreas: 'ManageAreas/SearchAreas',   
    InactiveAreas: 'ManageAreas/InactiveAreas', 
    GetAreasDetailsById  : 'ManageAreas/GetAreasDetailsById', 
    GetEditAreasDetailsById  : 'ManageAreas/GetEditAreasDetailsById', 
  },
  ManageMemberships: {
    SearchMembership: 'ManageMemberships/SearchMembership',
    SearchMembershipForFinance: 'ManageMemberships/SearchMembershipForFinance',
    UpdateStatus: 'ManageMemberships/MembershipStatusUpdate',
    UpdateLimit: 'ManageMemberships/UpdateLimit',
    GetMembershipDetails: 'ManageMemberships/MembershipDetails',
    GetMembershipHistory: 'ManageMemberships/GetMembershipHistory',
    PurchaseHistory: 'ManageMemberships/PurchaseHistory',
    SearchPurchases: 'ManageMemberships/SearchPurchases',
    ExportPurchases: 'ManageMemberships/ExportPurchases',
    UpdateExpireDate: 'ManageMemberships/UpdateExpireDate',
    UpdateEmiratesIdNumber: 'ManageMemberships/UpdateEmiratesIdNumber',
    MembershipReportRequest: 'ManageMemberships/GetMembershipReportRequestSummary'
  },
  ManageDraftMemberships: {
    SearchMembership: 'ManageDraftMemberships/SearchMembership',
    GetMembershipDetails: 'ManageDraftMemberships/MembershipDetails',
  },
  SalesPoint: {
    GetMembershipDetails: 'SalesPoint/GetMembershipDetails',
    MembershipTypes: 'SalesPoint/MembershipTypes',
    AllNationality: 'SalesPoint/AllNationality',
    AllReligion: 'SalesPoint/AllReligion',
    AddNewMembership: 'SalesPoint/AddNewMembership',
  },
  ManageNotifications:
  {
    SearchNotifications: 'ManageNotifications/searchnotifications',
    AddNotifications: 'ManageNotifications/AddNotification',
    UpdateReadStatus: 'ManageNotifications/UpdateReadStatus',
    TopNotifications: 'ManageNotifications/TopNotificationsForAdmin',
    UpdateAllReadStatus: 'ManageNotifications/UpdateAllReadStatus',
  },
  FileRequest:
  {
    AddFileOpening: 'ManageFileRequest/AddFileOpening',
    SearchFileReques: 'ManageFileRequest/SearchFileRequest',
    GetDetails: 'ManageFileRequest/FileDetails',
    ClientDocumentDetails: 'ManageFileRequest/ClientDocumentDetails',
    PrivateDocumentDetails: 'ManageFileRequest/PrivateDocumentDetails',
    SearchHistory: 'ManageFileRequest/SearchFileRequestHistory',
    UpdateStatus: 'ManageFileRequest/UpdateStatus',
    UpdateLiquorManager: 'ManageFileRequest/UpdateLiquorManager',
    UpdateLiquorLimit: 'ManageFileRequest/UpdateLiquorLimit',
    GetInspectTaskDetailsByClientId: 'ManageFileRequest/GetInspectTaskDetailsByClientId',
    GetNextLiquorLicenseNumber : 'ManageFileRequest/GetNextLiquorLicenseNumber',
    GetClinetNewFileRequestByClientId: 'ManageFileRequest/GetClinetNewFileRequestByClientId',
    GetInspectTaskListByClientId: 'ManageFileRequest/GetInspectTaskListByClientId',
    UpdatePaymentReceiptStatus: 'ManageFileRequest/UpdatePaymentReceiptStatus',
    UpdateInspectionStatus: 'ManageFileRequest/UpdateInspectionStatus',
    GetClientHistoryByClientId: 'ManageFileRequest/GetClientHistoryByClientId',
    MessageToTheClient: 'ManageFileRequest/MessageToTheClient',
    AllActiveClients: 'ManageFileRequest/AllActiveClients',
    AddTaskAssignment: 'ManageFileRequest/AddTaskAssignment',
    GetAllFileOpeningTask: 'ManageFileRequest/GetAllFileOpeningTask',
    SearchTask: 'ManageFileRequest/SearchTask',
    GetInspectForReportByClientId: 'ManageFileRequest/GetInspectForReportByClientId',
    GetFileOpeningPendingTask: 'ManageFileRequest/GetFileOpeningPendingTask',
    GetFileOpeningCompletedTask: 'ManageFileRequest/GetFileOpeningCompletedTask',
    ApprovalForClient: 'ManageFileRequest/ApprovalForClient',
    SearchRequest: 'ManageFileRequest/SearchClientRequestByRequestType',
    GetClinetNewFileRequestById :'ManageFileRequest/GetClinetNewFileRequestById',
    UpdateClientRequestStatus:'ManageFileRequest/UpdateClientRequestStatus',
    GetRequestHistoryDetailsById :'ManageFileRequest/GetRequestHistoryDetailsById',
    GetNumberOfClientForTradeLicence: 'ManageFileRequest/GetNumberOfClientForTradeLicence',
    GetReturnNotesById : 'ManageFileRequest/GetReturnNotesById',
    GetMyRequestByClientId: 'ManageFileRequest/GetMyRequestByClientId'
  },
  ManageGroups:
  {
    SearchGroups: 'ManageGroup/SearchGroups',
    AddUpdateGroups: 'ManageGroup/AddUpdateGroups',
  },
  Common:
  {
    ActorStatusUpdate: 'ManageEmployees/UpdateStatus',
    AllIPS: 'ManageAllowedIP/AllIPAddress',
    AddIP: 'ManageAllowedIP/AddIPAddress',
    DeleteIP: 'ManageAllowedIP/Delete',
    AllMembershipStatus: 'Common/MembershipStatus',
    HotelServices: 'Common/HotelServices',
    Groups: 'Common/Groups',
    FileOpeningStatus: 'Common/FileOpeningStatus',
    FileOpeningStatusForNew: 'Common/FileOpeningStatusForNew',
    FileOpeningStatusForApproved: 'Common/FileOpeningStatusForApproved',
    BusinessType: 'Common/BusinessType',
    RequestType: 'Common/RequestType',
    NotificationDetails: 'Common/NotificationDetails',
    MembershipType: 'Common/MembershipTypes',
    AllSalesPoints: 'Common/AllSalesPoint',
    AllDraftSalesPoints: 'Common/AllDraftSalesPoint',
    RequestCategory: 'Common/RequestCategory',
    AllCardStatuses: 'Common/AllCardStatuses',
    AllCardStatusesAdmin: 'Common/AllCardStatusesAdmin',
    AllAgents: 'Common/AllAgents',
    MemberShipRequestAndfileOpeningData:'Common/MemberShipRequestAndfileOpeningData',
    GenerateApplicationNumber: 'ManageFileRequest/GenerateApplicationNumber'
  },
  Dashboard: {
    MembershipRequest: 'Dashboard/GetMembershipRequestSummary',
    MembershipType: 'Dashboard/GetMembershipTypeSummary',
    AgentSummaryAll: 'Dashboard/GetAgentSummaryAll',
    FileOpening: 'Dashboard/GetFileOpeningSummary',
  },
  Messages: {
    TopMessages: 'Messages/GetTopMessages',
    ApprovedAgents: 'Messages/GetApprovedConnectUsers',
    UpdateReadMessages: 'Messages/UpdateReadMessages',
    UpdateReadMessagesAll: 'Messages/UpdateReadMessagesAll',
  },
  Export: {
    ExportExcel: 'Excel/ExportMembership',
    ExportExcelForFinancial: 'Excel/ExportExcelAdminFinancial',
    ExportExcelForPurchase: 'Excel/ExportExcelForPurchase',
  },
  ManageCardStatuses: {
    SearchCardStatus: 'CardStatuses/SearchCardStatus',
    AddNewCardStatus: 'CardStatuses/AddNewCardStatus',
    CardStatusDetails: 'CardStatuses/CardStatusDetails',
    GetNextId: 'CardStatuses/GetNextId',
    CardStatusHistory: 'CardStatuses/GetCardStatusHistory',
  },
  TaskManagement:{
    AddTask : 'TaskManagement/AddTask',
    TaskList : 'TaskManagement/TaskList',
    TaskStatus : 'TaskManagement/GetStatus',
    getTaskManagementDetailsByID : 'TaskManagement/getTaskManagementDetailsByID',
    getTaskManagementDetailsByIDForViewDeatils: 'TaskManagement/getTaskManagementDetailsByIDForViewDeatils',
    UpdateStatus : 'TaskManagement/UpdateStatus',
    GetTaskManagementHistory : 'TaskManagement/GetTaskManagementHistory',
    UploadImageOrVideo : 'TaskManagement/UploadImageOrVideo',
    GetTaskManagementCount : 'TaskManagement/GetTaskManagementCount',
    TaskRequest : 'TaskManagement/GetTaskManagementRequestSummary'
  }
};
